### ISSUE TITLE
CheckNet报错

### ISSUE THREAD

**Issue by Zonciu** [yearliny/myscript#1]
```
Traceback (most recent call last):
  File ".\CheckNet.py", line 48, in <module>
    apps_detail = get_apps_detail()
  File ".\CheckNet.py", line 27, in get_apps_detail
    app_display_name, _ = wr.QueryValueEx(key, "DisplayName")
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

**Comment by yearliny** [comment]
请提供系统版本以及Python版本信息，无法重现错误。

**Comment by Zonciu** [comment]
查找注册表发现有两个没有数据的项，DisplayName不存在，然后就报错了
